from .user import UserViewset
from .profesion import ProfesionViewset
from .grado import GradoViewset
from .curso import CursoViewset
from .nivel import NivelViewset
from .seccion import SeccionViewset
from .catedratico import CatedraticoViewset
from .estudiante import EstudianteViewset
from .asignacion import AsignacionViewset
from .ciclo import CicloViewset
from .asignacion_estudiente import AsignacionEstudianteViewset
from .material_clase import MaterialViewset
from .tarea import TareaViewset