# Generated by Django 2.2.15 on 2021-04-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210414_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Jose', max_length=50),
            preserve_default=False,
        ),
    ]
