# Generated by Django 2.2.15 on 2021-04-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210414_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='descripcion',
            new_name='curso_descripcion',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='curso_name',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='cilco',
            new_name='ciclo',
        ),
        migrations.RenameField(
            model_name='nivel',
            old_name='descripcion',
            new_name='nivel_descipcion',
        ),
        migrations.RenameField(
            model_name='nivel',
            old_name='nombre',
            new_name='nivel_name',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='nombre',
            new_name='rol_name',
        ),
        migrations.RenameField(
            model_name='seccion',
            old_name='nombre',
            new_name='seccion_name',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='descripcion',
        ),
    ]
