# Generated by Django 2.2.15 on 2021-04-19 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210414_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_rol', to='api.Rol'),
        ),
    ]
