# Generated by Django 2.2.15 on 2021-05-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210505_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='Material'),
        ),
        migrations.AlterField(
            model_name='tarea_estudiante',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='TareasEstudiante'),
        ),
    ]
