# Generated by Django 2.2.15 on 2021-05-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210505_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='Tarea'),
        ),
    ]
