# Generated by Django 2.2.15 on 2021-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210505_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_entrega',
            field=models.DateField(),
        ),
    ]
