# Generated by Django 2.2.15 on 2021-05-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210507_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea_estudiante',
            name='fecha_entrega',
            field=models.DateField(),
        ),
    ]
