from .profile import Profile
from .asignacion import Asignacion
from .asignacion-estudiante import Asignacion_Estudiante
from .catedratico import Catedratico
from .ciclo_escolar import Ciclo
from .curso import Curso
from .estudiante import Estudiante
from .evento import Evento
from .grado import Grado
from .material_de_clase import Material
from .nivel import Nivel
from .profesion import Profesion
from .rol import Rol
from .seccion import Seccion
from .tarea_estudiante import Tarea_Estudiante
from .tarea import Tarea
